version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

  worker:
    build:
      context: .
    network_mode: host
    command: celery -A tasks.index worker -l info --pool=solo
    depends_on:
      - app
      - rabbitmq
    volumes:
      - ./:/app

  beat:
    build:
      context: .
    network_mode: host
    command: celery -A tasks.index beat -l info
    depends_on:
      - app
      - rabbitmq
    volumes:
      - ./:/app

  app:
    build:
      context: .
    container_name: celery_app
    network_mode: host
    # ports:
    #   - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./:/app

networks:
  celery_net:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
