locations = ['Lisboa',
  	'Sintra',	
	'Vila Nova de Gaia',
	'Porto',	
	'Cascais',	
	'Loures',
	'Braga',
	'Almada',
	'Matosinhos',
	'Oeiras',
	'Amadora',
	'Seixal',
	'Gondomar',
	'Guimarães',	
	'Odivelas',	
	'Coimbra',
	'Vila Franca de Xira',	
	'Santa Maria da Feira',	
	'Maia',
	'Vila Nova de Famalicão',	
	'Leiria',	
	'Setúbal',	
	'Barcelos',	
	'Funchal',
	'Viseu',
	'Valongo',	
	'Mafra',	
	'Viana do Castelo',	
	'Paredes',	
	'Torres Vedras',	
	'Vila do Conde',	
	'Aveiro',	
	'Barreiro',
	'Loulé',
	'Penafiel',
	'Palmela',
	'Santo Tirso',
	'Faro',
	'Ponta Delgada',
	'Moita',
	'Oliveira de Azeméis',
	'Póvoa de Varzim',
	'Portimão',
	'Figueira da Foz',
	'Santarém',
	'Felgueiras',	
	'Montijo',
	'Paços de Ferreira',
	'Alcobaça',
	'Ovar',
	'Évora',
	'Sesimbra',
	'Castelo Branco',
	'Amarante',
	'Pombal',
	'Caldas da Rainha',
	'Vila Real',
	'Marco de Canaveses',
	'Fafe',
	'Lousada',
	'Vila Verde',
	'Covilhã',
	'Águeda',
	'Olhão',
	'Ourém',
	'Alenquer',
	'Albufeira',
	'Santa Cruz',
	'Ponte de Lima',
	'Guarda',
	'Ílhavo',
	'Marinha Grande',
	'Trofa',
	'Silves',
	'Chaves',
	'Tomar',
	'Esposende',
	'Bragança',
	'Abrantes',
	'Cantanhede',
	'Torres Novas',
	'Angra do Heroísmo',
	'Lagos',
	'Beja',
	'Câmara de Lobos',
	'Ribeira Grande',
	'Espinho',
	'Benavente',
	'Odemira',
	'Santiago do Cacém',
	'Anadia',
	'Tavira',
	'Fundão',
	'Peniche',
	'Lourinhã',
	'Estarreja',
	'Tondela',
	'Albergaria-a-Velha',
	'Montemor-o-Velho',
	'Lamego',
	'Vizela',
	'Lagoa',
	'Cartaxo',
	'Porto de Mós',
	'Oliveira do Bairro',
	'Vagos',
	'Portalegre',
	'São João da Madeira',
	'Almeirim',
	'Póvoa de Lanhoso',
	'Seia',
	'Salvaterra de Magos',	
	'Azambuja',	
	'Mirandela',	
	'Vale de Cambra',
	'Arouca',
	'Rio Maior',	
	'Elvas',	
	'Arcos de Valdevez',	
	'Entroncamento',	
	'Praia da Vitória',	
	'Oliveira do Hospital',	
	'Mealhada',	
	'Machico',
	'Alcochete',
	'Vila Real de Santo António',
	'Amares',
	'Mangualde',
	'Monção',
	'Cinfães',	
	'Celorico de Basto',
	'Baião',
	'Coruche',
	'Soure',
	'Lousã',
	'Condeixa-a-Nova',
	'Caminha',
	'Montemor-o-Novo',	
	'Castelo de Paiva',
	'Cabeceiras de Basto',	
	'Batalha',	
	'Ponte de Sor',	
	'São Pedro do Sul',	
	'Nazaré',
	'Sertã',	
	'Valpaços',	
	'Peso da Régua',	
	'Horta',	
	'Macedo de Cavaleiros',
	'Sines',	
	'Lagoa', 
	'Arruda dos Vinhos',	
	'Grândola',	
	'Serpa',	
	'Castro Daire',	
	'Valença',	
	'Cadaval',	
	'Moura',	
	'Nelas',	
	'Penacova',	
	'Bombarral',	
	'Ribeira Brava',	
	'Estremoz',
	'Alcanena',	
	'Gouveia',	
	'Mira',
	'Miranda do Corvo',	
	'Vieira do Minho',
	'Óbidos',	
	'Vila Pouca de Aguiar',
	'Ansião',
	'Sabugal',
	'São Brás de Alportel',
	'Vendas Novas',
	'Tábua',
	'Alcácer do Sal',
	'Sever do Vouga',
	'Arganil',
	'Ponte da Barca',
	'Sátão',
	'Calheta',
	'Santa Comba Dão',	
	'Sobral de Monte Agraço',
	'Alijó',
	'Murtosa',
	'Vila Franca do Campo',
	'Resende',
	'Reguengos de Monsaraz',
	'Vouzela',	
	'Oliveira de Frades',	
	'Moimenta da Beira',
	'Montalegre',	
	'Carregal do Sal',	
	'Mortágua',	
	'Vila Nova de Cerveira',
	'Aljustrel',	
	'Paredes de Coura',
	'Chamusca',
	'Trancoso',
	'Ponta do Sol',	
	'Idanha-a-Nova',	
	'Mogadouro',	
	'Pinhel',	
	'Campo Maior',	
	'Ferreira do Zêzere',	
	'Melgaço',	
	'Vinhais',	
	'Ferreira do Alentejo',
	'Vila Viçosa',	
	'Tarouca',	
	'Penalva do Castelo',
	'Proença-a-Nova',	
	'Vila Nova da Barquinha',
	'Alpiarça',	
	'Castro Verde',	
	'Torre de Moncorvo',	
	'Vila Nova de Poiares',	
	'São João da Pesqueira',	
	'Almodôvar',	
	'Arraiolos',	
	'Celorico da Beira',	
	'Santana',	
	'Miranda do Douro',	
	'Castro Marim',	
	'Borba',
	'Mação',
	'Mondim de Basto',	
	'Terras de Bouro',	
	'Madalena',
	'Vila Nova de Foz Côa',
	'Redondo',
	'Alvaiázere',
	'Mértola',
	'Belmonte',
	'Santa Marta de Penaguião',
	'Vila Flor',
	'Aljezur',	
	'Nisa',	
	'Ribeira de Pena',	
	'Almeida',	
	'Povoação',	
	'Portel',	
	'Vila do Bispo',	
	'Sernancelhe',	
	'Armamar',	
	'Sabrosa',	
	'Carrazeda de Ansiães',	
	'Monchique',	
	'Penela',	
	'Vila do Porto',
	'Golegã',
	'Viana do Alentejo',	
	'Figueiró dos Vinhos',
	'Murça',
	'Aguiar da Beira',
	'Vidigueira',	
	'Porto Santo',	
	'Figueira de Castelo Rodrigo',	
	'Tabuaço',	
	'Alandroal',
	'Boticas',
	'Velas',
	'Oleiros',
	'São Vicente',
	'Ourique',
	'Penamacor',
	'Vila Nova de Paiva',
	'Mêda',
	'Fornos de Algodres',
	'Cuba',
	'Nordeste',
	'Sousel',
	'Lajes do Pico',
	'Alfândega da Fé',
	'Vimioso',
	'Mora',
	'Santa Cruz da Graciosa',
	'Pampilhosa da Serra',
	'Avis',
	'Góis',
	'Constância',
	'Mesão Frio',
	'Sardoal',	
	'Calheta',
	'Gavião',
	'Pedrógão Grande',	
	'Vila Velha de Ródão',	
	'Vila de Rei',	
	'Crat',
	'São Roque do Pico',
	'Freixo de Espada à Cinta',
	'Castelo de Vide',
	'Alter do Chão',
	'Marvão',
	'Monforte',
	'Manteigas',
	'Fronteira',
	'Arronches',
	'Penedono',
	'Castanheira de Pera',
	'Alcoutim',
	'Porto Moniz',
	'Mourão',
	'Alvito',
	'Santa Cruz das Flores',
	'Barrancos',
	'Lajes das Flore',
	'Corvo',
]